import React from "react";
import type { Metadata } from "next";

/* components */
import Header from "@/components/Header";
// import Footer from "components/footer";
// import PageTop from "components/pageTop";

/* css */
import "@/css/global.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="jp">
      <body>
        <Header />
        <main>{children}</main>
        {/* <PageTop /> */}
        {/* <Footer /> */}
      </body>
    </html>
  );
};

export default RootLayout;
